'use strict'

const SET_ROUTE = 'set_route'
const SET_SIZE_STATUS = 'SET_SIZE_STATUS'
const SET_SIZE_VERTICAL = 'SET_SIZE_VERTICAL'
const SET_SIZE_HORIZONTAL = 'SET_SIZE_HORIZONTAL'
const HYDRATE = 'hydrate'

module.exports = {
	SET_ROUTE,
	SET_SIZE_STATUS,
	SET_SIZE_VERTICAL,
	SET_SIZE_HORIZONTAL,
	HYDRATE
}