'use strict'

const BORDER_RADIUS = '6px'
const BORDER_RADIUS_INNER = '4px'

const NAV_MIN_WIDTH = '200px'
const NAV_WIDTH = '300px'
const CONTENT_MIN_WIDTH = '300px'

const PREVIEW_MIN_HEIGHT = '200px'
const PREVIEW_HEIGHT = '60vh'
const INSPECTOR_MIN_HEIGHT = '300px'

const HEIGHT = '3.4em'

module.exports = {
	BORDER_RADIUS,
	BORDER_RADIUS_INNER,
	NAV_MIN_WIDTH,
	NAV_WIDTH,
	CONTENT_MIN_WIDTH,
	PREVIEW_MIN_HEIGHT,
	PREVIEW_HEIGHT,
	INSPECTOR_MIN_HEIGHT,
	HEIGHT
}