'use strict'

const NAV_MIN_WIDTH = '200px'
const NAV_WIDTH = '300px'
const CONTENT_MIN_WIDTH = '300px'

const PREVIEW_MIN_HEIGHT = '200px'
const PREVIEW_HEIGHT = '50vh'
const INSPECTOR_MIN_HEIGHT = '300px'

module.exports = {
	NAV_MIN_WIDTH,
	NAV_WIDTH,
	CONTENT_MIN_WIDTH,
	PREVIEW_MIN_HEIGHT,
	PREVIEW_HEIGHT,
	INSPECTOR_MIN_HEIGHT
}